### ISSUE TITLE
Viktor's secret

### ISSUE THREAD

**Issue by szepeviktor** [xwp/site-monorepo-example#1]
Hello @kasparsd!

Just a couple of days before I've summarized how to manage a WordPress installation.
https://github.com/szepeviktor/composer-managed-wordpress
Providing you want control over all files.

Please consider taking a look at it.

**Comment by kasparsd** [comment]
Thanks for sharing your work @szepeviktor!

This repo attempts to explore full-app mono repositories where all dependencies are developed as part of the same source tree. This gets pretty complicated when the dependencies are basically source files and need to have their JS/CSS built for a release and have a unified system for running unit tests for each dependency and for the app as a whole.

For more traditional workflows where all dependencies are added as release bundles, we have an example for WordPress VIP hosted projects here https://github.com/xwp/vip-go-site

**Comment by szepeviktor** [comment]
I see.
The development of a single plugin could be so noisy!

I'm not envy of you.
