### ISSUE TITLE
Add a directory for the document root

### ISSUE THREAD

**Issue by szepeviktor** [xwp/site-monorepo-example#2]
- configuration files and documents will live is a separate directory, not mixed with application code/directories
- e.g. `vendor` directory will be safe: above document root
- anything else could be stored in repo root

like [public](https://github.com/szepeviktor/composer-managed-wordpress/tree/master/public) in my repo

**Comment by kasparsd** [comment]
Yes, you're correct -- the `vendor` should live outside of the public root. Unfortunately some of the enterprise hosts such as WordPress VIP don't support placing anything below or outside of the public root. So for this prototype I left it like this.

**Comment by szepeviktor** [comment]
Very sad. 😿
